# Generated by Django 5.1.6 on 2025-02-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelDetails', '0002_profile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('travel_date', models.DateField()),
                ('return_date', models.DateField()),
                ('reason', models.TextField()),
                ('approval_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'TravelRequest',
                'verbose_name_plural': 'TravelRequests',
            },
        ),
    ]
