# Generated by Django 5.1.6 on 2025-02-12 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelDetails', '0003_travelrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelrequest',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='travelrequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='travelrequest',
            name='full_name',
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='form_location',
            field=models.CharField(default='salem', max_length=255, verbose_name='From Location'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
