# Generated by Django 5.1.6 on 2025-02-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelDetails', '0004_remove_travelrequest_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='booking_mode',
            field=models.CharField(choices=[('self', 'Self'), ('travel desk', 'Travel Desk')], default='self', max_length=20),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='travel_mode',
            field=models.CharField(choices=[('by train', 'By Train'), ('by flight', 'By Flight'), ('by bus', 'By Bus')], default='by flight', max_length=20),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
