# Generated by Django 5.1.6 on 2025-02-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravelDetails', '0005_travelrequest_booking_mode_travelrequest_travel_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelrequest',
            name='return_date',
        ),
    ]
