# Generated by Django 5.1.6 on 2025-02-12 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelDetails', '0006_remove_travelrequest_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='age',
            field=models.CharField(default='10', max_length=15, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='dob',
            field=models.DateField(default='1967-02-12'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='email',
            field=models.EmailField(default='john@gmail.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='full_name',
            field=models.CharField(default='', max_length=255, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=15),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='phone_no',
            field=models.CharField(default=0, max_length=50, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='travel_date',
            field=models.DateField(default='2025-02-12'),
        ),
    ]
