# Generated by Django 5.1.6 on 2025-02-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelDetails', '0007_travelrequest_age_travelrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Is Completed'),
        ),
    ]
